version: '3.8'
services:
  restapi:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SERVER_PORT: "${SERVER_PORT:-8080}"
      API_VERSION: "${API_VERSION:-v1}"
      DB_HOST: "db"
      DB_PORT: "${DB_PORT:-3306}"
      DB_USER: "${DB_USER:-restServer}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME:-RestApi}"
      LOG_DIR: "${LOG_DIR:-/var/log/restapi/}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRATION_TIME: "${JWT_EXPIRATION_TIME:-15m}"
      JWT_REFRESH_TOKEN_VALIDITY: "${JWT_REFRESH_TOKEN_VALIDITY:-7d}"
    depends_on:
      - db
  db:
    image: mariadb:11.2.2-jammy
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME:-RestApi}"
      MYSQL_USER: "${DB_USER:-restServer}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "${DB_PORT:-3306}:3306"
volumes:
  db_data:
